let collector1 = document.querySelector("#collector1");
let pen = collector1.getContext("2d");
// pen.fillStyle = "white";
// pen.fillRect(0, 0, 100, 100);
pen.strokeStyle = "white";
pen.lineWidth = 1;
pen.beginPath();
pen.moveTo(0, 20);
pen.lineTo(100, 20);
pen.stroke();
pen.closePath();
